/*----------------------------------------------------------------------------
 *      U S B  -  K e r n e l
 *----------------------------------------------------------------------------
 * Name:    usbdesc.c
 * Purpose: USB Descriptors
 * Version: V1.20
 *----------------------------------------------------------------------------
 *      This software is supplied "AS IS" without any warranties, express,
 *      implied or statutory, including but not limited to the implied
 *      warranties of fitness for purpose, satisfactory quality and
 *      noninfringement. Keil extends you a royalty-free right to reproduce
 *      and distribute executable files created using this software for use
 *      on NXP Semiconductors LPC family microcontroller devices only. Nothing
 *      else gives you the right to use this software.
 *
 * Copyright (c) 2009 Keil - An ARM Company. All rights reserved.
 *----------------------------------------------------------------------------
 * History:
 *          V1.20 Changed string descriptor handling
 *          V1.00 Initial Version
 *----------------------------------------------------------------------------*/

#include "Pixart_Sensor.h"

/* HID Report Descriptor */
const U8 HID_ReportDescriptorMouse[] =
{ 
// Generated by Dennis 5/6/2014 with padding for burst mode
0x05,0x01,//Usage Page (Generic Desktop)
    0x09,0x02,//Usage (Mouse)
    0xA1,0x01,//Collection (Application)
        0x09,0x01,//Usage (Pointer)
        0xA1,0x00,//Collection (Physical)
            // --- Mouse button --- 1st byte (byte 1)//

            0x05,0x09,//Usage Page (Button)
            0x19,0x01,//Usage Minimum (Button 1)
            0x29,0x03,//Usage Maximum (Button 3)
            0x15,0x00,//Logical Minimum (0)
            0x25,0x01,//Logical Maximum (1)
            0x95,0x03,//Report Count (3)
            0x75,0x01,///Report Size (1) 			
            0x81,0x02,//Input (Data,Var,Abs)

            // --- Padding for button ---//   
            0x95,0x01,//Report Count (1)
            0x75,0x05,//Report Size (5)
            0x81,0x01,//Input (Cnst,Ary,Abs)

            // --- Mouse XY --- 2nd, 3rd, 4th, 5th, (byte 4)//
            0x05,0x01,//Usage Page (Generic Desktop)
            0x09,0x30,//Usage (X)
            0x09,0x31,//sage (Y)
            0x16,0x01,0x80,///Logical Minimum (-32767)
            0x26,0xFF,0x7F,//Logical Maximum (32767)
            0x75,0x10,//Report Size (16)
            0x95,0x02,//Report Count (2)
            0x81,0x06,//Input (Data,Var,Rel)

            // --- Wheel --- 6th byte (byte 6)//
            0x09,0x38,//Usage (Wheel)
            0x15,0x81,//Logical Minimum(-127)
            0x25,0x7F,//Logical Maximum(127)
            0x75,0x08,//Report Size(8)
            0x95,0x01,//Report Count(1)
            0x81,0x06,//Input(Data,Var,Rel)    

#ifdef ENABLE_BURST_DAT_REPORT
			// --- Burst mode -- 
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,
			0x09, 0xC0,

			0x15, 0x81,                        //     Logical Minimum (-127)
			0x25, 0x7F,                        //     Logical Maximum (127)
			0x75, 0x08,                        //     Report Size (8)
			0x95, (U8)BURST_DATA_SIZE,         //     Report Count
			0x81, 0x06,                        //     Input (Data, Variable, Relative)
#endif
        0xC0,//End Collection
    0xC0,//End Collection     
};

const U16 HID_ReportDescMouseSize = sizeof(HID_ReportDescriptorMouse);


/* USB Standard Device Descriptor */
const U8 USB_DeviceDescriptor[] =
{
	USB_DEVICE_DESC_SIZE,/* bLength */
	USB_DEVICE_DESCRIPTOR_TYPE,/* bDescriptorType */
#if LPM_SUPPORT
	WBVAL(0x0201),/* 2.01 *//* bcdUSB */
#else
	WBVAL(0x0200),/* 2.00 *//* bcdUSB */
#endif
	0x00,/* bDeviceClass */
	0x00,/* bDeviceSubClass */
	0x00,/* bDeviceProtocol */
	USB_MAX_PACKET0,/* bMaxPacketSize0 */
	WBVAL(0x192F),/* idVendor *//* idVendor */
	WBVAL(0x0000),/* idProduct */
	WBVAL(0x0000),//WBVAL(0x0100),/* 1.00 *//* bcdDevice */
	0x01,/* iManufacturer */
	0x02,/* iProduct */
	0x00,/* iSerialNumber */
	0x01/* bNumConfigurations: one possible configuration*/
};

const U8 USB_ConfigDescriptor[] =
{
    /* Configuration 1 */
    USB_CONFIGUARTION_DESC_SIZE,/* bLength */
    USB_CONFIGURATION_DESCRIPTOR_TYPE,/* bDescriptorType */
    WBVAL(/* wTotalLength */
    USB_CONFIGUARTION_DESC_SIZE +

    USB_INTERFACE_DESC_SIZE +/*Mouse*/
    HID_DESC_SIZE +
    USB_ENDPOINT_DESC_SIZE
    ),
    0x01,/* bNumInterfaces */
    0x01,/* bConfigurationValue */
    0x00,/* iConfiguration */
    USB_CONFIG_BUS_POWERED,/* bmAttributes */
    USB_CONFIG_POWER_MA(100),/* bMaxPower */

    /* Interface 0, Alternate Setting 0, HID Class */
    USB_INTERFACE_DESC_SIZE,/* bLength */
    USB_INTERFACE_DESCRIPTOR_TYPE,/* bDescriptorType */
    0x00,/* bInterfaceNumber */
    0x00,/* bAlternateSetting */
    0x01,/* bNumEndpoints */
    USB_DEVICE_CLASS_HUMAN_INTERFACE,/* bInterfaceClass */
    HID_SUBCLASS_BOOT,/* bInterfaceSubClass */
    HID_PROTOCOL_MOUSE,/* bInterfaceProtocol */
    0x00,/* iInterface */
    /* HID Class Descriptor */
    /* HID_DESC_OFFSET = 0x0012 */
    HID_DESC_SIZE,/* bLength */
    HID_HID_DESCRIPTOR_TYPE,/* bDescriptorType */
    WBVAL(0x0111), /* 1.11 *//* bcdHID */
    0x00,/* bCountryCode */
    0x01,/* bNumDescriptors */
    HID_REPORT_DESCRIPTOR_TYPE,/* bDescriptorType */
    WBVAL(HID_REPORT_DESC_MOUSE_SIZE),/* wDescriptorLength */
    /* Endpoint, HID Interrupt In */
    USB_ENDPOINT_DESC_SIZE,/* bLength */
    USB_ENDPOINT_DESCRIPTOR_TYPE,/* bDescriptorType */
    USB_ENDPOINT_IN(HID_EP1_IN),/* bEndpointAddress */
    USB_ENDPOINT_TYPE_INTERRUPT,/* bmAttributes */
    //WBVAL(0x0008),/* wMaxPacketSize original 28/4/2014 code*/
	WBVAL(EP1_MAX_SIZE),/* wMaxPacketSize dennis added*/
    0x01,/* 1ms *//* bInterval */

 //   0/* bLength */
};

const U8 USB_StringDescriptor[] =
{
	/* Index 0x00: LANGID Codes */
	0x04,                              /* bLength */
	USB_STRING_DESCRIPTOR_TYPE,/* bDescriptorType*/
	WBVAL(0x0409), /* US English *//* wLANGID */
	/* Index 0x01: Manufacturer */
	(19*2 + 2),/* bLength (13 Char + Type + lenght)*/
	USB_STRING_DESCRIPTOR_TYPE,/* bDescriptorType*/
	'P',0,
	'i',0,
	'x',0,
	'A',0,
	'r',0,
	't',0,
	' ',0,
	'I',0,
	'm',0,
	'a',0,
	'g',0,
	'i',0,
	'n',0,
	'g',0,
	' ',0,
	'I',0,
	'n',0,
	'c',0,
	'.',0,
	/* Index 0x02: Product */
	(12*2 + 2),/* bLength ( 12 Char + Type + lenght) */	
	USB_STRING_DESCRIPTOR_TYPE,/* bDescriptorType */
	'G',0,
	'a',0,
	'm',0,
	'i',0,
	'n',0,
	'g',0,
	' ',0,
	'M',0,
	'o',0,
	'u',0,
	's',0,
	'e',0,
};

#if LPM_SUPPORT
/* In order to test Link Power Management(LPM), bcdUSB needs to be 0x0201(USB 2.0
Extension) instead of 0x0200. Below BOS descriptor is for LPM test only. However,
current USBC2.0 CV test requires both Super Speed Device Capability Descriptor
and Device Capability descriptor to be present and wSpeedSupport should be 0x000F
instead of 0x0003 indicating it's a Super Speed Device or USBCV test will fail.
For USB2.0 extention and LPM support, the device is not necessary a Super Speed
Device. To be discussed with USB-IF. */

/* USB BOS Descriptor */
const uint8_t USB_BOSDescriptor[] = {
  USB_BOS_DESC_SIZE,                 /* bLength */
  USB_BOS_TYPE,                      /* bDescriptorType, BOS */
  WBVAL(                             /* wTotalLength */
    USB_BOS_DESC_SIZE +
    USB_SS_DEVICE_CAPABILITY_SIZE +
    USB_DEVICE_CAPABILITY_SIZE
  ),
  0x02,                               /* bNumDeviceCaps, One Device Capability desc. */
  /* Device Capabilities, USB 2.0 Extension Descriptor */
  USB_SS_DEVICE_CAPABILITY_SIZE,     /* bLength */
  USB_DEVICE_CAPABILITY_TYPE,        /* bDescriptorType, DEVICE CAPABILITY */
  0x03,                              /* bDeviceCapabilityType, USB Super Speed */
  0x00,                              /* bmAttributes */
  WBVAL(0x000F),                     /* wSpeedsSupported, All speeds are supported. */
  0x02,                              /* bFunctionalitySupport, Full Speed */
  0x00,                              /* bU1DevExitLat */
  WBVAL(0x0000),                     /* bU2DevExitLat */
  /* Device Capabilities, USB 2.0 Extension Descriptor */
  USB_DEVICE_CAPABILITY_SIZE,        /* bLength */
  USB_DEVICE_CAPABILITY_TYPE,        /* bDescriptorType, DEVICE CAPABILITY */
  0x02,                              /* bDeviceCapabilityType, USB2.0 EXTENSION */
  (0x1<<1),                          /* bmAttributes, bit1 to 1, LPM supported. */
  0x00,
  0x00,
  0x00
};
#endif

